AimsLib/urls.py
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Development.urls')),
    path('', include('Paths.urls')),
    path('', include('Benchmark.urls')),
    path('', include('VideoLecture.urls')),
    path('', include('WrittenLecture.urls')),
    path('', include('QuestionGenerator.urls')),
    path('', include("Community.urls")),
    path('', include("Organisations.urls")),
    path('', include("WebsiteTools.urls")),
    path('', include("Library.urls")),
    path('', include("Interactions.urls")),
    path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("favicon.ico"))),
    path('Members/', include("django.contrib.auth.urls")),
    path('Members/', include('Members.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Library/urls.py
from django.urls import path
from .views import (LibraryView,
                    LibraryView_ajax_search_library,
                    LibraryView_ajax_get_library_result,
                    LibraryView_ajax_use_content,
                    LibraryView_ajax_get_user_bookmarks,
                    LibraryView_ajax_get_bookmark_content,
                    ajax_get_library_permissions,
                    ajax_edit_library_permissions
                    )

urlpatterns = [
    path("library/", LibraryView.as_view(), name="library"),
    path("LibraryView_ajax_search_library/",  LibraryView_ajax_search_library, name="library-search"),
    path("LibraryView_ajax_get_library_result/", LibraryView_ajax_get_library_result, name="library-result"),
    path("LibraryView_ajax_use_content/", LibraryView_ajax_use_content, name="library-use-content"),
    path("LibraryView_ajax_get_user_bookmarks/", LibraryView_ajax_get_user_bookmarks, name="library-get-bookmarks"),
    path("LibraryView_ajax_get_bookmark_content/", LibraryView_ajax_get_bookmark_content, name="library-load-bookmark"),
    path("ajax_get_library_permissions/", ajax_get_library_permissions, name="get-library-permissions"),
    path("ajax_edit_library_permissions/", ajax_edit_library_permissions, name="edit-library-permissions"),



]

Paths/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from .views import (PathsHomeView,
                    PathwayCreate,
                    PathwayContentCreate,
                    PathwayView,
                    PathwayDevelopView,
                    PathwayEdit,
                    get_dev_pathway_content,
                    edit_dev_pathway_content,
                    get_pathway_content_obj,
                    submit_content_setting_changes,
                    submit_content_delete,
                    UserPathways_ajax_get_pathway_costs,
                    UserPathways_ajax_check_pathway_invites,
                    UserPathways_ajax_submit_pathway_invite,
)

urlpatterns = [
    path('pathways/user', PathsHomeView.as_view(), name="pathways"),
    path('pathway/create', PathwayCreate.as_view(), name="pathway-create"),
    path('pathway/add_content/<int:pathway_id>/', PathwayContentCreate.as_view(), name="pathway-content-create"),
    path('pathway/<int:pathway_id>/', PathwayView.as_view(), name="pathway-view"),
    path('pathway/develop/<int:pathway_id>/', PathwayDevelopView.as_view(), name="pathway-develop"),
    path('pathway/update/<int:pk>/', PathwayEdit.as_view(), name="pathway-edit"),
    path('get_dev_pathway_content/', get_dev_pathway_content, name="pathway-dev-content-get"),
    path('dev_pathway_edit/', edit_dev_pathway_content, name="pathway-dev-content-edit"),
    path('ajax_get_pathway_content_obj/', get_pathway_content_obj, name="pathway-dev-content-modal-edit"),
    path('ajax_submit_content_setting_changes/', submit_content_setting_changes, name="content-setting-changes-submit"),
    path('ajax_submit_delete_pathway_content/', submit_content_delete, name="submit-content-delete"),
    path("UserPathways_ajax_get_pathway_costs/", UserPathways_ajax_get_pathway_costs, name="get-pathway-costs"),
    path("UserPathways_ajax_check_pathway_invites/", UserPathways_ajax_check_pathway_invites, name="check-pathway-invites"),
    path("UserPathways_ajax_submit_pathway_invite/", UserPathways_ajax_submit_pathway_invite, name="submit-pathway-invite"),


]

Library/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404
from Paths.models import Pathway
from VideoLecture.models import VideoLecture
from WrittenLecture.models import Article
from Benchmark.models import Benchmark
from Development.models import Aim, Behaviour, StepTracker
from Organisations.models import Organisation
from django.views.generic import View


# Create your models here.
LIBRARY_CONTENT_TYPES = (("Article","Article"),
                        ("VideoLecture","Video"),
                        ("Benchmark","Benchmark"),
                        ("Pathway","Pathway"),
                        ("Organisation","Organisation"),
                        ("Aim","Aim"),
                        ("Behaviour", "Behaviour"),
                        ("StepTracker", "StepTracker"))
class LibraryContentType(models.Model):
    content_type = models.CharField(max_length=100)
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['content_type'], name='unique_content_type')
        ]
    def __str__(self):
        return f"LCT_{self.id}_{self.content_type}"



class Bookmark(models.Model):
    for_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="bookmarks")
    content_type = models.CharField(max_length=100, choices=LIBRARY_CONTENT_TYPES)
    article = models.ForeignKey(Article, on_delete=models.CASCADE, null=True, blank=True)
    video = models.ForeignKey(VideoLecture, on_delete=models.CASCADE, null=True, blank=True)
    benchmark = models.ForeignKey(Benchmark, on_delete=models.CASCADE, null=True, blank=True)
    pathway = models.ForeignKey(Pathway, on_delete=models.CASCADE, null=True, blank=True)
    organisation = models.ForeignKey(Organisation, on_delete=models.CASCADE, null=True, blank=True)
    aim = models.ForeignKey(Aim, on_delete=models.CASCADE, null=True, blank=True)
    behaviour =  models.ForeignKey(Behaviour, on_delete=models.CASCADE, null=True, blank=True)
    steptracker =  models.ForeignKey(StepTracker, on_delete=models.CASCADE, null=True, blank=True)
    create_date = models.DateField(auto_now=False,auto_now_add=True)
    create_time = models.TimeField(auto_now=False,auto_now_add=True)

    @property
    def bookmarked_object(self):
        if self.content_type == "Article":
            return self.article
        elif self.content_type == "VideoLecture":
            return self.video
        elif self.content_type=="Benchmark":
            return self.benchmark
        elif self.content_type =="Pathway":
            return self.pathway
        elif self.content_type =="Organisation":
            return self.organisation
        elif self.content_type =="Aim":
            return self.aim
        elif self.content_type == "Behaviour":
            return self.video
        elif self.content_type == "StepTracker":
            return self.video
        else:
            return "no_object_found"


class LibraryPermission(models.Model):
    # For what content
    content_type = models.CharField(max_length=100, choices=LIBRARY_CONTENT_TYPES)
    article = models.OneToOneField(Article, on_delete=models.CASCADE, null=True, blank=True, related_name="permissions")
    video = models.OneToOneField(VideoLecture, on_delete=models.CASCADE, null=True, blank=True, related_name="permissions")
    benchmark = models.OneToOneField(Benchmark, on_delete=models.CASCADE, null=True, blank=True, related_name="permissions")
    pathway = models.OneToOneField(Pathway, on_delete=models.CASCADE, null=True, blank=True, related_name="permissions")
    organisation = models.OneToOneField(Organisation, on_delete=models.CASCADE, null=True, blank=True, related_name="permissions")
    aim = models.OneToOneField(Aim, on_delete=models.CASCADE, null=True, blank=True, related_name="permissions")
    behaviour =  models.OneToOneField(Behaviour, on_delete=models.CASCADE, null=True, blank=True, related_name="permissions")
    steptracker =  models.OneToOneField(StepTracker, on_delete=models.CASCADE, null=True, blank=True, related_name="permissions")
    create_date = models.DateField(auto_now=False,auto_now_add=True)
    create_time = models.TimeField(auto_now=False,auto_now_add=True)


    # For Viewing - constraint can't be viewed unless previewewd true
    can_be_viewed_in_library = models.BooleanField(default=False)

    # For Using -  constraint bookmarked has to be true to be able to add to external content
    can_be_used  = models.BooleanField(default=False)

    # For visibility
    author_visibility_hidden = models.BooleanField(default=True)

Library/templates/edit_library_permissions_modal.html
<div class="modal fade" id="LibraryPermissionModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="LibraryPermissionModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="LibraryPermissionModalLabel">Library Permissions</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="container" id="currentLibraryPermissions" style="display: none;">
          <p>This content has the following library permissions: </p>
          <p><strong>Content can be viewed in library:</strong>  <span id="canBeViewedInLibrary"></span></p>
          <p><strong>Content can used:</strong> <span id="canBeUsedInLibrary"></span></p>
          <p><strong>Author visibility is hidden:</strong> <span id="authorVisibilityHidden"></span></p>
          <button type="button" class="btn btn-al w-100 my-2" id="editCurrentPermissionsLaunch">Edit permissions</button>
          <div class="container" id="editCurrentLibraryPermissions" style="display: none;">
            <form method="POST">
              {% csrf_token %}
              <input type="hidden" id="LibraryPermissionId"></input>
              <div class="form-check form-switch">
                <input class="form-check-input" type="checkbox" role="switch" id="id_edit_can_be_viewed_in_library">
                <label class="form-check-label" for="id_edit_can_be_viewed_in_library">Content can be viewed in library. Users will be able to view and bookmark your content in the library.</label>
              </div>
              <br>
              <div class="form-check form-switch">
                <input class="form-check-input" type="checkbox" role="switch" id="id_edit_can_be_used">
                <label class="form-check-label" for="id_edit_can_be_used">This content is useable. Users can add bookmarked pathways to organisations, assign pathway content to their own pathways and make copies of aims to their own profiles.</label>
              </div>
              <br>
              <div class="form-check form-switch">
                <input class="form-check-input" type="checkbox" role="switch" id="id_edit_author_visibility_hidden">
                <label class="form-check-label" for="id_edit_author_visibility_hidden">Hide the author of this content (Aims authors are always hidden)</label>
              </div>
              <br>
            </form>
            <button type="button" name="submitEditLibraryPermission" class="btn btn-al w-100 my-2">Overwrite with new permissions</button>
            <button type="button" class="btn btn-al w-100 my-2" name="closeEditCurrentPermissionsLaunch">Cancel & close</button>

          </div>
        </div>
        <div class="container" id="activateLibraryPermissions" style="display: none;">
          <p>There are no permissions set. This item is not visible in the library. Submit the form below to set permissions.</p>
          <form method="POST">
            {% csrf_token %}
            <div class="form-check form-switch">
              <input class="form-check-input" type="checkbox" role="switch" id="id_can_be_viewed_in_library">
              <label class="form-check-label" for="id_can_be_viewed_in_library">Content can be viewed in library. Users will be able to view and bookmark your content in the library.</label>
            </div>
            <br>
            <div class="form-check form-switch">
              <input class="form-check-input" type="checkbox" role="switch" id="id_can_be_used">
              <label class="form-check-label" for="id_can_be_used">This content is useable. Users can add bookmarked pathways to organisations, assign pathway content to their own pathways and make copies of aims to their own profiles.</label>
            </div>
            <br>
            <div class="form-check form-switch">
              <input class="form-check-input" type="checkbox" role="switch" id="id_author_visibility_hidden">
              <label class="form-check-label" for="id_author_visibility_hidden">Hide the author of this content (Aims authors are always hidden)</label>
            </div>
            <br>
            <button class="btn btn-al w-100" name="activateLibraryPermission" type="submit">Activate library permissions</button>
          </form>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

Library/templates/library_view.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Library{% endblock %}

{% block topcarousel %}
{% endblock %}

{% block pageInfoCaro %}
{% endblock pageInfoCaro %}


{% block pageInfo_title %}
LIBRARY
{% endblock pageInfo_title %}

{% block pageInfo_message %}
The library is a collection of user created Aims, Pathways  & Organisations. You can search for content you wish to join or create a copy of the anonmously provided aims.  In the future external inpirational content will be included
{% endblock pageInfo_message %}



{% block content %}
<div class="container my-4">

  <input class="form-control w-100 mb-4"  type="text" id="searchInput" placeholder="Search the library..">

<div class="my-2">


  <ul class="nav nav-pills nav-justified" id="resultsTab" role="tablist">

    <li class="nav-item p-1" role="presentation">
      <button class="nav-link p-1 active" name="filterContentType" id="all-results-tab" data-bs-toggle="tab" data-bs-target="#allResults" type="button" role="tab" aria-controls="allResults" aria-selected="true">All</button>
    </li>

    <li class="nav-item p-1" role="presentation">
      <button class="nav-link p-1 ms-auto me-auto" name="filterContentType"  id="aims-tab" data-bs-toggle="tab" data-bs-target="#aimsTab" type="button" role="tab" aria-controls="aimsTab" aria-selected="false">Aims</button>
    </li>
    <li class="nav-item p-1" role="presentation">
      <button class="nav-link p-1 ms-auto me-auto" name="filterContentType"  id="behaviours-tab" data-bs-toggle="tab" data-bs-target="#behavioursTab" type="button" role="tab" aria-controls="behavioursTab" aria-selected="false">Behaviours</button>
    </li>

    <li class="nav-item p-1" role="presentation">
      <button class="nav-link p-1 ms-auto me-auto" name="filterContentType"  id="steptrackers-tab" data-bs-toggle="tab" data-bs-target="#stepTrackerTab" type="button" role="tab" aria-controls="stepTrackerTab" aria-selected="false"> Trackers</button>
    </li>
    <li class="nav-item p-1" role="presentation">
      <button class="nav-link p-1 ms-auto me-auto" name="filterContentType" id="pathways-tab" data-bs-toggle="tab" data-bs-target="#pathwaysTab" type="button" role="tab" aria-controls="pathwaysTab" aria-selected="false">Pathways</button>
    </li>

    <li class="nav-item p-1" role="presentation">
      <button class="nav-link p-1 ms-auto me-auto" name="filterContentType" id="articles-tab" data-bs-toggle="tab" data-bs-target="#articlesTab" type="button" role="tab" aria-controls="articlesTab" aria-selected="false">Articles</button>
    </li>

    <li class="nav-item p-1" role="presentation">
      <button class="nav-link p-1 ms-auto me-auto" name="filterContentType" id="video-tab" data-bs-toggle="tab" data-bs-target="#videoTab" type="button" role="tab" aria-controls="videoTab" aria-selected="false">Videos</button>
    </li>

    <li class="nav-item p-1" role="presentation">
      <button class="nav-link p-1 ms-auto me-auto" name="filterContentType" id="benchmarks-tab" data-bs-toggle="tab" data-bs-target="#benchmarksTab" type="button" role="tab" aria-controls="benchmarksTab" aria-selected="false">Benchmarks</button>
    </li>

    <li class="nav-item p-1" role="presentation">
      <button class="nav-link p-1 ms-auto me-auto" name="filterContentType"  id="organisation-tab" data-bs-toggle="tab" data-bs-target="#organisationsTab" type="button" role="tab" aria-controls="organisationsTab" aria-selected="false">Organisations</button>
    </li>
  </ul>
</div>
  <div class="tab-content" id="resultsTabContent">


    <div class="tab-pane fade show active" id="allResults" role="tabpanel" aria-labelledby="all-results-tab">
      <ul class="list-group-flush" id="AllResultsList">
      </ul>

      <div class="col  border border-primary rounded">
        <h5 class="card-title my-2 text-center">ALL BOOKMARKS</h5>
        <ul class="list-group-flush px-0 bookmarkresultlist" name="bookmarkType" id="AllUserBookmarks">
        </ul>
      </div>

    </div>

    <div class="tab-pane fade" id="aimsTab" role="tabpanel" aria-labelledby="aims-tab">
      <ul class="list-group-flush resultlist" id="AimResultsList">
      </ul>

      <div class="col  border border-primary rounded">
        <h5 class="card-title my-2 text-center">AIM BOOKMARKS</h5>
        <ul class="list-group-flush px-0 bookmarkresultlist" name="bookmarkType"  id="AimUserBookmarks">
        </ul>
      </div>
    </div>


    <div class="tab-pane fade" id="behavioursTab" role="tabpanel" aria-labelledby="behaviours-tab">
      <ul class="list-group-flush resultlist" id="BehaviourResultsList">
      </ul>

      <div class="col  border border-primary rounded">
        <h5 class="card-title my-2 text-center">BEHAVIOUR BOOKMARKS</h5>
        <ul class="list-group-flush px-0 bookmarkresultlist" name="bookmarkType"  id="BehaviourUserBookmarks">
        </ul>
      </div>
    </div>

    <div class="tab-pane fade" id="stepTrackerTab" role="tabpanel" aria-labelledby="steptracker-tab">
      <ul class="list-group-flush resultlist" id="StepTrackerResultsList">
      </ul>

      <div class="col  border border-primary rounded">
        <h5 class="card-title my-2 text-center">STEP TRACKER BOOKMARKS</h5>
        <ul class="list-group-flush px-0 bookmarkresultlist" name="bookmarkType"  id="StepTrackerUserBookmarks">
        </ul>
      </div>
    </div>
    <div class="tab-pane fade" id="pathwaysTab" role="tabpanel" aria-labelledby="pathways-tab">
      <ul class="list-group-flush resultlist" id="PathwayResultsList">
      </ul>
      <div class="col  border border-primary rounded">
        <h5 class="card-title my-2 text-center">PATHWAY BOOKMARKS</h5>
        <ul class="list-group-flush px-0 bookmarkresultlist" name="bookmarkType" id="PathwayUserBookmarks">
        </ul>


      </div>
    </div>

    <div class="tab-pane fade" id="articlesTab" role="tabpanel" aria-labelledby="articles-tab">
      <ul class="list-group-flush resultlist" id="ArticleResultsList">
      </ul>

          <div class="col  border border-primary rounded">
            <h5 class="card-title my-2 text-center">ARTICLE BOOKMARKS</h5>
            <ul class="list-group-flush px-0 bookmarkresultlist" name="bookmarkType"  id="ArticleUserBookmarks">
            </ul>
          </div>
      </div>

    <div class="tab-pane fade" id="videoTab" role="tabpanel" aria-labelledby="video-tab">
      <ul class="list-group-flush resultlist" id="VideoResultsList">
      </ul>
      <div class="col  border border-primary rounded">
        <h5 class="card-title my-2 text-center">VIDEO BOOKMARKS</h5>
        <ul class="list-group-flush px-0 bookmarkresultlist" name="bookmarkType" id="VideoUserBookmarks">
        </ul>
      </div>
    </div>

    <div class="tab-pane fade" id="benchmarksTab" role="tabpanel" aria-labelledby="benchmarks-tab">
      <ul class="list-group-flush resultlist" id="BenchmarkResultsList">
      </ul>
      <div class="col  border border-primary rounded">
        <h5 class="card-title my-2 text-center">BENCHMARK BOOKMARKS</h5>
        <ul class="list-group-flush px-0 bookmarkresultlist" name="bookmarkType"  id="BenchmarkUserBookmarks">
        </ul>

      </div>
    </div>

    <div class="tab-pane fade" id="organisationsTab" role="tabpanel" aria-labelledby="organisation-tab">
      <ul class="list-group-flush resultlist" id="OrganisationResultsList">
      </ul>
      <div class="col  border border-primary rounded">
        <h5 class="card-title my-2 text-center">ORGANISATION BOOKMARKS</h5>

        <ul class="list-group-flush px-0 bookmarkresultlist" name="bookmarkType"  id="OrganisationUserBookmarks">
        </ul>

      </div>
    </div>

  </div>


</div>

{% include "view_aim_result_modal.html" %}
{% include "view_behaviour_result_modal.html" %}
{% include "view_steptracker_result_modal.html" %}
{% include "view_pathway_result_modal.html" %}
{% include "view_article_result_modal.html" %}
{% include "view_video_result_modal.html" %}
{% include "view_benchmark_result_modal.html" %}
{% include "view_organisation_result_modal.html" %}
{% endblock %}
{% block scripts %}
<script src="{% static 'js/library/libraryView.js' %}"></script>

{% endblock scripts %}

Library/templates/view_aim_result_modal.html
<div class="modal fade" id="viewLibraryAimResultModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="viewLibraryAimResultModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="viewLibraryAimResultModalLabel">Aim from library</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <ul class="list-group-flush px-0">
          <li class="list-group-item">
            <strong>Aim: </strong><span  id="aimTitle"></span>
          </li>
          <li class="list-group-item">
            <strong>Motivation: </strong><span id="aimMotivation"></span>
          </li>
          <li class="list-group-item">
            <strong>Behaviours: </strong> <ul class="list-group-flush px-0" id="aimBehaviours">
            </ul>
          </li>
          <ul>

      </div>
      <div class="modal-footer">
        <form method="POST">
          {% csrf_token %}
        <button type="submit" class="btn btn-al" name="submitCopyAim" id="submitCopyAim">Copy</button>
        <button type="submit" class="btn btn-al" name="submitBookmark" id="submitBookmarkAim">Bookmark</button>
        <button type="submit" class="btn btn-al" name="deleteBookmark" id="deleteAimBookmark"><i class="far fa-trash-alt"></i> Delete bookmark</button>
      </form>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

Library/templates/view_article_result_modal.html
<div class="modal fade" id="viewLibraryArticleResultModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="viewLibraryArticleResultModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="viewLibraryArticleResultModalLabel">Article from library</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <ul class="list-group-flush px-0" id="articleDetails">
          </ul>

          <p><small><strong>Bookmarking</strong> this article will allow you to create a copy to use on one of your own pathways. Copied articles cannot be  used in pathways that charge a fee.
          </small></p>

      </div>
      <div class="modal-footer">
        <form method="POST">
          {% csrf_token %}
        <button type="submit" class="btn btn-al" name="submitBookmark" id="submitBookmarkArticle">Bookmark</button>
        <button type="submit" class="btn btn-al" name="deleteBookmark" id="deleteArticleBookmark"><i class="far fa-trash-alt"></i></button>
      </form>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-al" name="addArticleToForm">Select this article</button>
      </div>
    </div>
  </div>
</div>

Library/templates/view_behaviour_result_modal.html
<div class="modal fade" id="viewLibraryBehaviourResultModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="viewLibraryBehaviourResultModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="viewLibraryBehaviourResultModalLabel">Behaviour from library</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <ul class="list-group-flush px-0">
          <li class="list-group-item">
            <strong>Behaviour: </strong><span  id="behaviourTitle"></span>
          </li>
          <li class="list-group-item">
            <strong>Trackers: </strong>
            <ul class="list-group-flush px-0" id="behaviourTrackers">
            </ul>
          </li>
        </ul>
          <p><small><strong>Bookmarking</strong> this behaviour will allow you to create a copy on one of your own aims. It will include all the trackers the orignal author has assigned it. You'll be able to edit your copy of the behaviour and trackers upon assigning it to an aim. Copied content will not appear in the library.
          </small></p>

      </div>
      <div class="modal-footer">
        <form method="POST">
          {% csrf_token %}
        <button type="submit" class="btn btn-al" name="submitBookmark" id="submitBookmarkBehaviour">Bookmark</button>
        <button type="submit" class="btn btn-al" name="deleteBookmark" id="deleteBehaviourBookmark"><i class="far fa-trash-alt"></i></button>
      </form>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

Library/templates/view_benchmark_result_modal.html
<div class="modal fade" id="viewLibraryBenchmarkResultModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="viewLibraryBenchmarkResultModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="viewLibraryBenchmarkResultModalLabel">Benchmark from library</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <ul class="list-group-flush px-0" id="benchmarkDetails">
          </ul>

          <p><small><strong>Bookmarking</strong> this benchmark will allow you to create a copy to use on one of your own pathways. Copied benchmarks cannot be  used in pathways that charge a fee.
          </small></p>

      </div>
      <div class="modal-footer">
        <form method="POST">
          {% csrf_token %}
        <button type="submit" class="btn btn-al" name="submitBookmark" id="submitBookmarkBenchmark">Bookmark</button>
        <button type="submit" class="btn btn-al" name="deleteBookmark" id="deleteBenchmarkBookmark"><i class="far fa-trash-alt"></i></button>
      </form>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-al" name="addBenchmarkToForm">Select this benchmark</button>
      </div>
    </div>
  </div>
</div>